### ISSUE TITLE
sparse_mmad.cu的一些困惑

### ISSUE THREAD

**Issue by HURONG0510** [lenLRX/AmpereSparseMatmul#1]
sparse_mmad.cu中
` :
  : "l"(d_ptr), "l"(a_ptr), "l"(b_ptr), "l"(c_ptr), "r"(metadata) //"l"表示u64 .reg, "r"表示u32 .reg
  : "memory");
`
这些ptr数组都是half类型的，为什么要用"l" 也即是u64去声明呢？

**Comment by lenLRX** [comment]
这里传的是half*,不是half,传指针给里面的ld指令用的
